planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]

       GridBased:
      plugin: "nav2_smac_planner::SmacPlannerHybrid"
      motion_model_for_search: "REEDS_SHEPP"
      minimum_turning_radius: 0.8
      allow_unknown: true

controller_server:
  ros__parameters:
    controller_frequency: 20.0
    controller_plugins: ["FollowPath"]

       FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"

      batch_size: 2000
      time_steps: 56
      model_dt: 0.05

      vx_max: 1.0
      vx_min: -0.5
      wz_max: 1.0

      critics:
        - ConstraintCritic
        - GoalCritic
        - GoalAngleCritic
        - PathAlignCritic
        - PathFollowCritic
        - PathAngleCritic
        - PreferForwardCritic
bt_navigator:
  ros__parameters:

global_costmap:
  global_costmap:
    ros__parameters:

local_costmap:
  local_costmap:
    ros__parameters: